steps:
  - name: Compile Win16 binaries
    image: ghcr.io/arlaneenalra/watcom-docker
    commands:
      - apk add --no-cache imagemagick
      - cd tests && make win16

  - name: Run integration tests
    image: python:${PYTHON_VERSION}-alpine
    commands:
      - apk add --no-cache imagemagick make mingw-w64-gcc i686-mingw-w64-gcc
      - pip install .[thumbnailer,win16]
      - cd tests && make
      - python3 -m unittest discover . --verbose

when:
  event: [tag, push, pull_request]

matrix:
  PYTHON_VERSION:
    - 3.10
    - 3.14
