clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      # Fetch the full history so that `git describe --tags` is not empty
      depth: 0
      tags: true

steps:
  - commands:
      - pip install .[dev] awscli
      - pdoc --no-show-source -o ./html/ icoextract/*.py '!icoextract.version' --footer-text "icoextract $(git describe --tags)"
      - aws s3 cp html/ s3://jlu5-ci-doc/ --recursive
    image: python:3.14
    name: Upload API docs
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_ENDPOINT_URL_S3: https://s3.us-west-000.backblazeb2.com

when:
  - event: tag
  - event: push
    branch: wip/doc-*

depends_on:
- check
