steps:
  - commands:
      - pip install build twine
      - python3 -m build
      - twine upload --username __token__ dist/*
    image: python:3.14
    name: Upload release to PyPI
    environment:
      TWINE_PASSWORD:
        from_secret: pypi_token

when:
  event: [tag]

depends_on:
- check
